name: CI

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run Jest with coverage
      run: |
        npx jest --coverage
        coverage=$(cat coverage/lcov.info | grep "Statements" | awk '{print $4}' | sed 's/%//')
        if (( $(echo "$coverage < 95" |bc -l) )); then exit 1; fi


